/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jrapl_EnergyCheckUtils */

#ifndef _Included_jrapl_EnergyCheckUtils
#define _Included_jrapl_EnergyCheckUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jrapl_EnergyCheckUtils
 * Method:    ProfileInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jrapl_EnergyCheckUtils_ProfileInit
  (JNIEnv *, jclass);

/*
 * Class:     jrapl_EnergyCheckUtils
 * Method:    GetSocketNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jrapl_EnergyCheckUtils_GetSocketNum
  (JNIEnv *, jclass);

/*
 * Class:     jrapl_EnergyCheckUtils
 * Method:    EnergyStatCheck
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jrapl_EnergyCheckUtils_EnergyStatCheck
  (JNIEnv *, jclass);

/*
 * Class:     jrapl_EnergyCheckUtils
 * Method:    ProfileDealloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jrapl_EnergyCheckUtils_ProfileDealloc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
